name: C/C++ CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install SQLite
      run: sudo apt-get install -y sqlite3 libsqlite3-dev
      
    - name: Create database
      run: sqlite3 automasters.db < database.sql
      
    - name: Create directories
      run: mkdir -p bin
      
    - name: Compile main app
      run: make
      
    - name: Run all tests
      run: make test
      
    - name: Run tests with coverage
      run: |
        sudo apt-get install -y lcov
        make test-coverage
        lcov --capture --directory . --output-file coverage.info --ignore-errors mismatch
        lcov --list coverage.info
